In [ ]:
#Declaring random Input, Bias and Weights
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2

In [ ]:
#The output will look like this
output=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias)
print(output)

Neural networks typically have layers that consist of more than one neuron. Layers are nothing 
more than groups of neurons. Each neuron in a layer takes exactly the same input

In [ ]:
#Making 3 neuron with 4 inputs
inputs=[1,2,3,5]

weights1=[0.5,0.23,-0.4,0.66]
weights2=[0.1,-0.4,0.9,-0.44]
weights3=[-0.3,0.6,-0.22,0.54]

bias1=2
bias2=1.5
bias3=0.5

output=[
    inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
    inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
    inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3
]
print(output)

In [ ]:
#Making a better code with loops
inputs=[1,0.5,2.5,4]
weights=[[0.3,0.4,-0.22,0.45],
         [0.45,0.23,-0.44,0.8],
         [0.81,0.56,-0.55,0.78]]
biases=[2,3,3.6]
layer_outputs=[]
for neuron_bias,neuron_weights in zip(biases,weights):
    neuron_output=0
    for n_inputs,n_weight in zip(inputs,neuron_weights):
        neuron_output += n_inputs*n_weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)

A tensor object is an object that can be represented as an array.

In [ ]:
#DOT Product in python
A=[1,2,3]
B=[3,-2,5]
output=0
for i,j in zip(A,B):
    output += i*j
print(output)

In [ ]:
#single neuron with numpy
import numpy as np
inputs=[1.0,2.0,3.0,2.5]
weights=[0.2,0.45,0.33,-0.67]
biases=2.0
output=np.dot(inputs,weights)+biases
print(output)

In [ ]:
#Multiple neuron with numpy
inputs=[1.0,2.5,3.5,2.2]
weights=[[0.2,0.45,0.33,-0.5],
         [0.35,-0.56,0.67,-0.88],
         [0.23,0.65,-0.77,0.28]]
biases=[1.0,3.5,2.4]
output=np.dot(weights,inputs)+biases
print(output)

In [ ]:
#Transpose with numpy and getting dot product
a=[1,2,3]
b=[2,3,4]
a=np.array([a])
b=np.array([b]).T
np.dot(a,b)

In [ ]:
inputs = [[1, 2, 3, 2.5], [2., 5., -1., 2], [-1.5, 2.7, 3.3, -0.8]] 
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]] 
biases = [2, 3, 0.5] 
weights2 = [[0.1, -0.14, 0.5], 
            [-0.5, 0.12, -0.33], 
            [-0.44, 0.73, -0.13]] 
biases2 = [-1, 2, -0.5]

Layer_output1=np.dot(inputs,np.array(weights).T)+biases
Layer_output2=np.dot(Layer_output1, np.array(weights2).T)+biases2
print(Layer_output2)

### Dense Layer Class

Next, let’s explore np.random.randn ​ and np.zeros ​ in more detail. These methods are 
convenient ways to initialize arrays. np.random.randn ​ produces a Gaussian distribution with a 
mean of 0 and a variance of 1, which means that it’ll generate random numbers, positive and 
negative, centered at 0 and with the mean value close to 0. In general, neural networks work best 
with values between -1 and +1, which we’ll discuss in an upcoming chapter. So this 
np.random.randn ​ generates values around those numbers. We’re going to multiply this 
Gaussian distribution for the weights by 0.01​ to generate numbers that are a couple of 
magnitudes smaller.

When we pass data through a model from beginning to end, this is called a 
forward pass.

In [37]:
import numpy as np
class Layer_Dense:
    def __init__(self, n_input,n_neuron):
        self.weight=0.01*np.random.randn(n_input,n_neuron)
        self.bias=np.zeros((1,n_neuron))
    def forward(self,inputs):
        self.output= np.dot(inputs, self.weight)+self.bias
        return self.output

In [38]:
print(0.01*np.random.randn(3,3))

[[-0.01334258 -0.01346717  0.00693773]
 [-0.00159573 -0.00133702  0.01077744]
 [-0.01126826 -0.00730678 -0.0038488 ]]


In [40]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
X,y =spiral_data(samples=100, classes=3)
Dense1=Layer_Dense(2,3)
op=Dense1.forward(X)
print(op)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.04751882e-04  1.13953611e-04 -4.79834998e-05]
 [-2.74148420e-04  3.17291502e-04 -8.69217984e-05]
 [-4.21883655e-04  5.26662567e-04 -5.59126820e-05]
 [-5.77076804e-04  7.14014051e-04 -8.94304394e-05]
 [-3.54306976e-04  3.50254879e-04 -2.33634812e-04]
 [-8.92670010e-04  1.07678759e-03 -1.94532375e-04]
 [-9.33507807e-04  1.07238023e-03 -3.12273973e-04]
 [-1.12437585e-03  1.31128007e-03 -3.36296740e-04]
 [-1.33869553e-03  1.62009057e-03 -2.81017943e-04]
 [-1.48779724e-03  1.79484230e-03 -3.23859538e-04]
 [-1.20035873e-03  1.58119109e-03  8.65937000e-06]
 [-1.56528328e-03  1.99173321e-03 -1.30997345e-04]
 [-1.85718178e-03  2.30642664e-03 -2.70479388e-04]
 [-1.78093580e-03  2.27836682e-03 -1.24245722e-04]
 [-1.85300526e-03  2.38476763e-03 -1.00471654e-04]
 [-6.99865050e-04  1.11472746e-03  3.96097894e-04]
 [-2.19024252e-03  2.79446482e-03 -1.68075712e-04]
 [-1.69829139e-03  2.29598465e-03  1.31671681e-04]
 [-2.60229013e-03  3.27291898e-

### Making a RELU actiavtion function

In [44]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100] 
output = [] 
output= np.maximum(0,inputs)
print(output) 

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [46]:
class Activation_Relu():
    def forward(self,inputs):
        self.output=np.maximum(0,inputs)
        return self.output

### Making a dense layer with actvation

In [48]:
X,y = spiral_data(samples=100,classes=3)
dense1= Layer_Dense(2,3)
activation1=Activation_Relu()
op1=dense1.forward(X)
op2=activation1.forward(op1)
print(op2)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.37668263e-04 0.00000000e+00 0.00000000e+00]
 [2.21874667e-04 0.00000000e+00 0.00000000e+00]
 [4.07695799e-04 0.00000000e+00 0.00000000e+00]
 [5.45410847e-04 0.00000000e+00 0.00000000e+00]
 [7.06143677e-04 0.00000000e+00 0.00000000e+00]
 [7.77872046e-04 0.00000000e+00 0.00000000e+00]
 [6.49500405e-04 2.80898657e-05 0.00000000e+00]
 [1.08075328e-03 0.00000000e+00 0.00000000e+00]
 [1.27865677e-03 0.00000000e+00 0.00000000e+00]
 [1.42300932e-03 0.00000000e+00 0.00000000e+00]
 [1.55442092e-03 0.00000000e+00 0.00000000e+00]
 [1.67643931e-03 0.00000000e+00 0.00000000e+00]
 [1.84334186e-03 0.00000000e+00 0.00000000e+00]
 [1.54295389e-03 0.00000000e+00 0.00000000e+00]
 [7.94126754e-05 0.00000000e+00 0.00000000e+00]
 [1.63805950e-03 0.00000000e+00 0.00000000e+00]
 [1.50953222e-03 0.00000000e+00 0.00000000e+00]
 [2.03391653e-03 0.00000000e+00 0.00000000e+00]
 [1.36490085e-03 0.00000000e+00 0.00000000e+00]
 [3.82690516e-04 0.00000000e+00 0.000000

### Softmax function

In [50]:
layer_outputs = [4.8, 1.21, 2.385] 
exp_values=np.exp(layer_outputs)
print("Exponential values are")
print(exp_values)
norm_values= exp_values/np.sum(exp_values)
print("Exponential normlized values")
print(norm_values)

Exponential values are
[121.51041752   3.35348465  10.85906266]
Exponential normlized values
[0.89528266 0.02470831 0.08000903]


address what axis ​and keepdims ​mean

Let’s first discuss the axis​. Axis is 
easier to show than tell, but, in a 2D array/matrix, axis 0 refers to the rows, and axis 1 refers to 
the columns

In [52]:
layer_outputs = np.array([[4.8, 1.21, 2.385], 
                          [8.9, -1.81, 0.2], 
                          [1.41, 1.051, 0.026]]) 
 
print('Sum without axis') 
print(np.sum(layer_outputs)) 
 
print('This will be identical to the above since default is None:') 
print(np.sum(layer_outputs, axis=None))

Sum without axis
18.172
This will be identical to the above since default is None:
18.172


Next, axis​=0. This means to sum row-wise, along axis 0. In other words, the output 
has the same size as this axis, as at each of the positions of this output, the values from all the 
other dimensions at this position are summed to form it.

In [54]:
print('Another way to think of it w/ a matrix == axis 0: columns:') 
print(np.sum(layer_outputs, axis=0)) 

Another way to think of it w/ a matrix == axis 0: columns:
[15.11   0.451  2.611]


sum along axis 1

In [55]:
print('So we can sum axis 1, but note the current shape:') 
print(np.sum(layer_outputs, axis=1))

So we can sum axis 1, but note the current shape:
[8.395 7.29  2.487]


In [56]:
print('Sum axis 1, but keep the same dimensions as input:') 
print(np.sum(layer_outputs, axis=1, keepdims=True))

Sum axis 1, but keep the same dimensions as input:
[[8.395]
 [7.29 ]
 [2.487]]


Final Softmax function

In [57]:
class Activation_Softmax:
    def forward(self,inputs):
        exp_values=np.exp(inputs)
        norm_values=exp_values/np.sum(exp_values, axis=1, keepdims=True)
        self.output=norm_values
        return norm_values

### Calculating Loss

Categorical Cross-Entropy Loss

In [59]:
import math
softmax_op=[0.7,0.1,0.1]
target_op=[1,0,0]
loss=-(math.log(softmax_op[0])*target_op[0]+
        math.log(softmax_op[1])*target_op[1]+
        math.log(softmax_op[2])*target_op[2]
        )
print(loss)

0.35667494393873245


In [64]:
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output,y)
        data_loss= np.mean(sample_losses)
        return data_loss

In [ ]:
class Loss_CategoricalCrossentropy(Loss):
    def forward(self,y_pred)